spring.application.name=backend
# H2 Database
spring.datasource.url=jdbc:h2:tcp://localhost/~/slidtodo
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ?? ??
server.port=9090

# logging
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind= trace

# JWT CONFIGURATION

# JWT ??? ??? ?? ? (?? 32? ?? ??)
jwt.secret=cb6761b6115bb44f48d10f20f4af9b97beefd81860adc03729c9aa2090b32c36

# Access Token ?? ?? (1?? = 3600000ms)
jwt.access-token-expiration=3600000

# Refresh Token ?? ?? (7? = 604800000ms)
jwt.refresh-token-expiration=604800000